#This file handles compiling the container and instructing EC2 instance to download it.
name: Build and Deploy FastAPI Container Image

on:
  push:
    branches: [ main ]
    paths-ignore:
      - 'model_artifacts/model.safetensors'
      - '*.ipynb'
      - 'README.md'
      - 'images/*'
      - '.gitignore'
env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout Source Code
        uses: actions/checkout@v4

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and Push Docker Image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest
      - name: Execute Remote SSH Commands on EC2
        uses: appleboy/ssh-action@v1.0.3
        env:
          GHCR_TOKEN: ${{ secrets.GITHUB_TOKEN }} # secret in the action's environment loop
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ec2-user
          key: ${{ secrets.EC2_SSH_KEY }}
          envs: GHCR_TOKEN    #plugin to securely pass this variable over SSH
          script: |
            # Using the secure environment variable on EC2 host
            docker login ghcr.io -u tathavms -p $GHCR_TOKEN
            
            # newly built code image layer
            docker pull ghcr.io/tathavms/tweet_sentiment_analysis:latest
            
            # old running container stopped and erased
            #|| true acts as an error bypass. It tells the runner: "Try to delete the container. If it's not found, ignore the warning and keep moving forward to step 6 anyway."

            docker rm -f tweet_app || true
            
            # new container using the existing host model file mount
            docker run -d \
              --name tweet_app \
              -p 8000:8000 \
              -v /home/ec2-user/tweet_sentiment_analysis/model_artifacts/model.safetensors:/app/model_artifacts/model.safetensors \
              --restart unless-stopped \
              ghcr.io/tathavms/tweet_sentiment_analysis:latest

            # Deleting only the orphaned, legacy code layers left behind by the pull(EC2 space constraint)
            docker image prune -f